### PR TITLE
Drop support for EOL Python 2.7 and 3.5

### PR DESCRIPTION
**Pull request by hugovk**

### CODE REVIEW

**Comment by hugovk** [comment]
Any idea why Windows linting fails? It passes on Linux.

**Comment by domdfcoding** [comment]
GitHub actions has `autocrlf` set to true on Windows, so git is converting the line endings to CRLF, and `yamllint` then complains.

https://github.com/actions/checkout/issues/135

**Comment by hugovk** [comment]
Thanks! The suggestion at https://github.com/actions/checkout/issues/135#issuecomment-602171132 fixes it.

**Comment by flub** [comment]
lgtm, but unfortunately now has some conflicts as i merged some other PRs.  mind resolving these?

**Comment by hugovk** [comment]
Resolved!

**Comment by flub** [comment]
thanks!

**Comment by flub** [comment]
btw, bonus points for referencing the #dropthedot #savethedot fun ;)

**Pull request merged**
