### PR TITLE
Fix linting

### PR DESCRIPTION
**Pull request by nicoddemus**

### CODE REVIEW

**Comment by nicoddemus** [comment]
I suggest we drop the `linting` jobs and configure the repository to use pre-commit.ci instead. We have been using in pytest itself and a number of plugins, and are very happy with it.

**Review by flub — APPROVED** [review]

**Comment by flub** [comment]
> I suggest we drop the `linting` jobs and configure the repository to use pre-commit.ci instead. We have been using in pytest itself and a number of plugins, and are very happy with it.

sure, i don't really mind.  all these linting jobs were also contributed i think, so feel free to copy the setup from pytest or other plugins if it works well.

**Comment by flub** [comment]
you're now admin as well just in case that's needed for this :smile:   though probably only .github/workflow changes neeed

**Comment by nicoddemus** [comment]
Thanks, done: https://github.com/pytest-dev/pytest-timeout/pull/119.

**Pull request merged**
